from django.db import models
import json


class ImageGeneration(models.Model):
    """Store image generation request records"""
    user_text = models.TextField(verbose_name="User Input Text")
    target_style = models.CharField(max_length=200, verbose_name="Target Style")
    processed_prompt = models.TextField(verbose_name="LLM Processed Prompt", blank=True)
    ad_json = models.TextField(verbose_name="Generated Ad JSON", blank=True, help_text="Complete ad information JSON generated by LLM")
    image_path = models.CharField(max_length=500, verbose_name="Generated Image Path", blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    
    class Meta:
        verbose_name = "Image Generation Record"
        verbose_name_plural = "Image Generation Records"
        ordering = ['-created_at']
    
    def get_ad_json_dict(self):
        """Convert JSON string to dictionary"""
        if self.ad_json:
            try:
                return json.loads(self.ad_json)
            except json.JSONDecodeError:
                return {}
        return {}

