# Generated by Django 4.2.7 on 2025-12-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_text", models.TextField(verbose_name="用户输入文字")),
                (
                    "target_style",
                    models.CharField(max_length=200, verbose_name="目标风格"),
                ),
                (
                    "processed_prompt",
                    models.TextField(blank=True, verbose_name="LLM处理后的提示词"),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="生成的图像路径"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "图像生成记录",
                "verbose_name_plural": "图像生成记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
