# Generated by Django 4.2.7 on 2025-12-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegeneration",
            name="ad_json",
            field=models.TextField(
                blank=True,
                help_text="LLM生成的完整广告信息JSON",
                verbose_name="生成的广告JSON",
            ),
        ),
    ]
